<?php
/**
 * Created by PhpStorm.
 * User: xpwu
 * Date: 2019/3/23
 * Time: 11:07 PM
 */

namespace Inte;


use Inte\Annotation\AbstractProcessor;

class AnnotationProcessor {
  function __construct(string $repo, string $annotationProcessor) {
  }

  public function getServer(): AbstractProcessor {

  }

  /**
   * @return array [Dependence]
   */
  public function getDependencies(): array {

  }




}