<?php
/**
 * Created by PhpStorm.
 * User: xpwu
 * Date: 2019/3/23
 * Time: 10:47 PM
 */

namespace Inte;


class DependenceProcessor {
  function __construct(string $repo, array $dependencies) {
  }

  public function checkDependencies():bool {

  }

  public function mergeDependencies() {

  }

  public function loadDependencies() {

  }

  public function printDependencies() {

  }

  /**
   * @param string $targetDir
   * @return [class=>file]
   */
  public function buildDependencies(string $buildDir):array {

  }

}